youtubedl: /usr/local/bin/youtube-dl
python: /usr/bin/python3
params:
    - --no-playlist
    - --no-warnings
    - --playlist-end
    - 1
convert: true
avconv: /usr/bin/ffmpeg
uglyUrls: false
stream: true
remux: true
